import React, { useState } from 'react';
import SectionHeader from '../components/SectionHeader';

const POLICY_SECTIONS = [
  { id: 1, name: 'Scope & Purpose', desc: 'Define what this policy covers and why.', fields: [{ key: 'scope', label: 'What does this policy cover?', ph: 'e.g., All use of AI tools by employees including generative AI, automation tools, and AI-assisted decision making...' }, { key: 'purpose', label: 'Why does this policy exist?', ph: 'e.g., To ensure responsible AI use that protects company data, maintains compliance, and maximizes productivity...' }] },
  { id: 2, name: 'Approved Tools', desc: 'List sanctioned AI tools and their approved use cases.', fields: [{ key: 'tools', label: 'Approved AI tools', ph: 'e.g., ChatGPT Enterprise, Claude for Business, GitHub Copilot...' }, { key: 'cases', label: 'Approved use cases', ph: 'e.g., Content drafting, code assistance, data analysis, research summarization...' }] },
  { id: 3, name: 'Data Handling', desc: 'Rules for what data can and cannot be shared with AI tools.', fields: [{ key: 'allowed', label: 'Data types allowed', ph: 'e.g., Public information, de-identified data, general business content...' }, { key: 'prohibited', label: 'Data types prohibited', ph: 'e.g., PII, financial records, trade secrets, customer data, credentials...' }] },
  { id: 4, name: 'Quality Assurance', desc: 'How AI outputs are verified before use.', fields: [{ key: 'review', label: 'Review requirements', ph: 'e.g., All AI outputs must be reviewed by a human before external use...' }, { key: 'verification', label: 'Verification steps', ph: 'e.g., Fact-check all statistics, verify citations exist, check for bias...' }] },
  { id: 5, name: 'Compliance', desc: 'Regulatory and legal requirements.', fields: [{ key: 'regulations', label: 'Applicable regulations', ph: 'e.g., GDPR, CCPA, HIPAA, EU AI Act, industry-specific requirements...' }, { key: 'requirements', label: 'Compliance requirements', ph: 'e.g., Maintain audit logs, conduct quarterly impact assessments...' }] },
  { id: 6, name: 'Training', desc: 'Employee training requirements.', fields: [{ key: 'required', label: 'Required training', ph: 'e.g., All employees must complete AI responsible use training within 30 days...' }, { key: 'ongoing', label: 'Ongoing education', ph: 'e.g., Quarterly updates on AI policy changes, annual recertification...' }] },
  { id: 7, name: 'Incident Response', desc: 'What to do when things go wrong.', fields: [{ key: 'reporting', label: 'How to report incidents', ph: 'e.g., Contact IT security team immediately. Use incident form #AI-001...' }, { key: 'response', label: 'Response procedures', ph: 'e.g., Contain the issue, assess data exposure, notify affected parties...' }] },
  { id: 8, name: 'Governance', desc: 'Who oversees AI use and how the policy evolves.', fields: [{ key: 'owner', label: 'Policy owner', ph: 'e.g., Chief Technology Officer with AI Governance Committee...' }, { key: 'review_cycle', label: 'Review cycle', ph: 'e.g., Quarterly review, annual comprehensive update, triggered review on major AI developments...' }] },
];

export default function PolicyGenerator({ markComplete }) {
  const [currentStep, setCurrentStep] = useState(0);
  const [values, setValues] = useState({});
  const completed = POLICY_SECTIONS.filter((s, i) => s.fields.every(f => (values[`${i}-${f.key}`] || '').trim().length > 5)).length;

  const generatePolicy = () => {
    let doc = '# AI Use Policy\n\nGenerated by JSE AI Mastery Companion\n\n';
    POLICY_SECTIONS.forEach((s, i) => {
      doc += `## ${i + 1}. ${s.name}\n\n`;
      s.fields.forEach(f => { doc += `### ${f.label}\n${values[`${i}-${f.key}`] || '[Not provided]'}\n\n`; });
    });
    return doc;
  };

  const handleDownload = () => {
    const blob = new Blob([generatePolicy()], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a'); a.href = url; a.download = 'AI_Use_Policy.md'; a.click();
    if (markComplete) markComplete('policy-generator');
  };

  return (
    <div className="space-y-6" data-testid="policy-generator-exercise">
      <SectionHeader eyebrow="TIER 4 — ENTERPRISE" title="AI Use Policy Generator" />
      <p className="text-sm" style={{ color: 'var(--jse-muted)' }}>Walk through all 8 policy elements and generate a downloadable policy document.</p>
      <div className="flex items-center gap-3"><div className="jse-progress flex-1"><div className="jse-progress-fill" style={{ width: `${(completed / 8) * 100}%`, background: 'var(--jse-teal)' }} /></div><span className="mono-label" style={{ color: 'var(--jse-teal)', fontSize: '0.65rem' }}>{completed}/8 SECTIONS</span></div>
      <div className="flex gap-2 flex-wrap">
        {POLICY_SECTIONS.map((s, i) => (
          <button key={i} onClick={() => setCurrentStep(i)} className="px-3 py-1.5 rounded-lg mono-label text-xs" style={{ background: i === currentStep ? 'var(--jse-teal-deep)' : 'var(--jse-card)', border: `1px solid ${i === currentStep ? 'var(--jse-teal)' : 'rgba(255,255,255,0.05)'}`, color: i === currentStep ? 'var(--jse-teal)' : 'var(--jse-muted)', fontSize: '0.55rem' }}>{i + 1}</button>
        ))}
      </div>
      <div className="exercise-card">
        <div className="mono-label mb-1" style={{ color: 'var(--jse-teal)', fontSize: '0.6rem' }}>SECTION {currentStep + 1} OF 8</div>
        <h3 className="text-lg font-semibold mb-2" style={{ fontFamily: 'var(--font-display)' }}>{POLICY_SECTIONS[currentStep].name}</h3>
        <p className="text-sm mb-4" style={{ color: 'var(--jse-muted)' }}>{POLICY_SECTIONS[currentStep].desc}</p>
        {POLICY_SECTIONS[currentStep].fields.map(f => (
          <div key={f.key} className="mb-3"><label className="mono-label block mb-1" style={{ color: 'var(--jse-gold)', fontSize: '0.55rem' }}>{f.label}</label><textarea value={values[`${currentStep}-${f.key}`] || ''} onChange={e => setValues(prev => ({...prev, [`${currentStep}-${f.key}`]: e.target.value}))} placeholder={f.ph} className="jse-textarea" rows={3} /></div>
        ))}
      </div>
      <div className="flex gap-3">
        {currentStep > 0 && <button onClick={() => setCurrentStep(prev => prev - 1)} className="jse-btn-secondary">Previous</button>}
        {currentStep < 7 && <button onClick={() => setCurrentStep(prev => prev + 1)} className="jse-btn-teal">Next Section</button>}
        {completed >= 6 && <button onClick={handleDownload} className="jse-btn-gold" data-testid="primary-action-button">Download Policy</button>}
      </div>
    </div>
  );
}
